### ISSUE TITLE
fix: broken pipe error with local filesystem broker / result backend

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#270]
Sometimes when running with local FS as broker / result backend (which is the default when running on worker mode), we get:

First error:
```
Traceback (most recent call last):
  File "/home/osboxes/.local/bin/secator", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/decorators.py", line 305, in func
    runner.run()
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/runners/_base.py", line 217, in run
    return list(self.__iter__())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/runners/_base.py", line 226, in __iter__
    for item in self.yielder():
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/runners/task.py", line 70, in yielder
    yield from task
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/runners/_base.py", line 640, in process_live_tasks
    for data in Runner.get_live_results(result):
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/runners/_base.py", line 531, in get_live_results
    yield from Runner.get_celery_results(result)
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/runners/_base.py", line 555, in get_celery_results
    data = get_task_data(task_id)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/secator/runners/_helpers.py", line 127, in get_task_data
    chunk = res.info.get('chunk', '')
            ^^^^^^^^^^^^
AttributeError: 'BrokenPipeError' object has no attribute 'get'
```

Second error:
```
   File "/home/osboxes/Workspace/secator/secator/celery.py", line 281, in run_command
    task = task_cls(targets, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/osboxes/Workspace/secator/secator/runners/command.py", line 161, in __init__
    self._print(self.cmd.replace('[', '\['), color='bold cyan', rich=True)
   File "/home/osboxes/Workspace/secator/secator/runners/_base.py", line 784, in _print
    data = f'{self.prefix:>15} {data}' if self.prefix and not self.print_item else data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/rich/console.py", line 1673, in print
    with self:
   File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/rich/console.py", line 865, in __exit__
    self._exit_buffer()
   File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/rich/console.py", line 823, in _exit_buffer
    self._check_buffer()
   File "/home/osboxes/.local/pipx/venvs/secator/lib/python3.11/site-packages/rich/console.py", line 2060, in _check_buffer
    self.file.write(text)
 BrokenPipeError: [Errno 32] Broken pipe
 ```

Those seem to come from Celery itself breaking pipes because we don't get them on Redis / RabbitMQ backends.

**Comment by ocervell** [comment]
Fixed by https://github.com/freelabz/secator/pull/334
