### ISSUE TITLE
error output on console

### ISSUE THREAD

**Issue by Naboot42** [freelabz/secator#499]
Exception ignored in: <generator object Command.yielder at 0x7f09aa151580>
Traceback (most recent call last):
  File "/home/nabot/secator/secator/runners/_base.py", line 273, in __iter__
    yield from self._process_item(item)
RuntimeError: generator ignored GeneratorExit
Traceback (most recent call last):
  File "/home/nabot/secator/.venv/bin/secator", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/secator/decorators.py", line 394, in func
    runner.run()
  File "/home/nabot/secator/secator/runners/_base.py", line 249, in run
    return list(self.__iter__())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/secator/runners/_base.py", line 284, in __iter__
    self.add_result(error, print=True)
  File "/home/nabot/secator/secator/runners/_base.py", line 320, in add_result
    self.output += repr(item) + '\n'
                   ^^^^^^^^^^
  File "/home/nabot/secator/secator/output_types/error.py", line 36, in __repr__
    return rich_to_ansi(s)
           ^^^^^^^^^^^^^^^
  File "/home/nabot/secator/secator/utils.py", line 352, in rich_to_ansi
    tmp_console.print(text, end='', soft_wrap=True)
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/rich/console.py", line 1679, in print
    renderables = self._collect_renderables(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/rich/console.py", line 1539, in _collect_renderables
    self.render_str(
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/rich/console.py", line 1429, in render_str
    rich_text = render_markup(
                ^^^^^^^^^^^^^^
  File "/home/nabot/secator/.venv/lib/python3.11/site-packages/rich/markup.py", line 167, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[//.source+//ert//.source]' at position 38 doesn't match any open tag

**Comment by LighTend3r** [comment]
Hello, what is the context of your error ?

**Comment by Naboot42** [comment]
Hi, it's an error from a new tool i want to implement.

**Comment by LighTend3r** [comment]
Show me the code of your new tool

**Comment by ocervell** [comment]
This issue arises when the outputs of a tool contains rich-like markup like `[bold` or `[anything` with a non-closed tag at the end.

I think we need to escape the strings output from tools before we try to call their `repr` method.
